# Generated by Django 6.0.6 on 2026-06-16 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_created',
            new_name='is_completed',
        ),
    ]
